### ISSUE TITLE
With latest qemu update(2.11-rc2) libvirt unable to list host-model support

### ISSUE THREAD

**Issue by sathnaga** [open-power-host-os/libvirt#10] opened 2017-11-24 12:11 UTC
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=161676 </cde:info>

qemu-kvm-2.10.92-1.dev.git7209583.el7.centos.ppc64le
$qemu-kvm  -version
QEMU emulator version 2.10.92
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

libvirt: libvirt-3.9.0-1.dev.git2c30e7b.el7.centos.ppc64le (irrespective of libvirt version to 3.6 or 3.9 this happens with 2.11 qemu)
```
# virsh domcapabilities
<domainCapabilities>
  <path>/usr/bin/qemu-kvm</path>
  <domain>kvm</domain>
  <machine>pseries-2.11</machine>
  <arch>ppc64le</arch>
  <vcpu max='1024'/>
  <os supported='yes'>
    <loader supported='yes'>
      <enum name='type'>
        <value>rom</value>
        <value>pflash</value>
      </enum>
      <enum name='readonly'>
        <value>yes</value>
        <value>no</value>
      </enum>
    </loader>
  </os>
  <cpu>
    <mode name='host-passthrough' supported='yes'/>
    <mode name='host-model' supported='no'/>
    <mode name='custom' supported='no'/>
  </cpu>
```

Old: qemu-kvm-2.10.0-2.rel.gitc334a4e.el7.centos.ppc64le
$ qemu-kvm -version
QEMU emulator version 2.10.0
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```
 virsh domcapabilities
<domainCapabilities>
  <path>/usr/bin/qemu-kvm</path>
  <domain>kvm</domain>
  <machine>pseries-2.10</machine>
  <arch>ppc64le</arch>
  <vcpu max='1024'/>
  <os supported='yes'>
    <loader supported='yes'>
      <enum name='type'>
        <value>rom</value>
        <value>pflash</value>
      </enum>
      <enum name='readonly'>
        <value>yes</value>
        <value>no</value>
      </enum>
    </loader>
  </os>
  <cpu>
    <mode name='host-passthrough' supported='yes'/>
    <mode name='host-model' supported='yes'>
      <model fallback='allow'>POWER8</model>
      <vendor>IBM</vendor>
    </mode>
    <mode name='custom' supported='yes'>
      <model usable='unknown'>POWER9</model>
      <model usable='unknown'>POWER8</model>
      <model usable='unknown'>POWER7</model>
    </mode>
  </cpu>
```

**Comment by cdeadmin** [comment] 2017-11-27 18:55
------- Comment From seg@us.ibm.com 2017-11-27 13:48:57 EDT-------
This would seem to be a qemu bug, not libvirt.

**Comment by cdeadmin** [comment] 2017-11-27 19:35
------- Comment From seg@us.ibm.com 2017-11-27 14:30:18 EDT-------
(In reply to comment #5)
&gt; This would seem to be a qemu bug, not libvirt.
Maybe not. I will look at this.

**Comment by cdeadmin** [comment] 2017-11-28 22:45
------- Comment From seg@us.ibm.com 2017-11-28 17:44:52 EDT-------
I believe this is commit 7bca16937ab3f5f3404b6f83106863e941599a14 which is in the current hostos-devel tree already, so I'm puzzled.  Looking some more.

**Comment by cdeadmin** [comment] 2017-12-01 01:15
------- Comment From seg@us.ibm.com 2017-11-30 20:13:07 EDT-------
Patch posted internally. After comment, shiva can push to hostos-devel.  I will be on vacation for the next two weeks; assuming all is OK, I will post patches upstream then. No hurry to do it earlier, I think, since we're in freeze for libvirt 3.10 anyway.

------- Comment (attachment only) From seg@us.ibm.com 2017-11-30 20:15:31 EDT-------

**Comment by cdeadmin** [comment] 2017-12-15 08:25
------- Comment From bssrikanth@in.ibm.com 2017-12-15 03:22:13 EDT-------
[root@ltczzj1 ~]# uname -r
4.14.0-1.rel.git68b4afb.el7.centos.ppc64le

[root@ltczzj1 ~]# virsh domcapabilities | grep -i host-model
    &lt;mode name='host-model' supported='yes'&gt;

**Comment by cdeadmin** [comment] 2017-12-18 09:55
------- Comment From satheera@in.ibm.com 2017-12-18 04:47:16 EDT-------
(In reply to comment #14)
&gt; [root@ltczzj1 ~]# uname -r
&gt; 4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
&gt; 
&gt; [root@ltczzj1 ~]# virsh domcapabilities | grep -i host-model
&gt;     &lt;mode name='host-model' supported='yes'&gt;

Does this available already in the libvirt version?(In reply to comment #14)
&gt; [root@ltczzj1 ~]# uname -r
&gt; 4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
&gt; 
&gt; [root@ltczzj1 ~]# virsh domcapabilities | grep -i host-model
&gt;     &lt;mode name='host-model' supported='yes'&gt;

This is devel only issue at this moment as it occurred after qemu update to qemu 2.11, and I guess libvirt fix for this yet not available in release branch, we might get this issue in release branch once we have qemu update to 2.11.

@Shiva,
Pls correct if otherwise.

Regards,
-Satheesh.

**Comment by cdeadmin** [comment] 2017-12-20 12:15
------- Comment From satheera@in.ibm.com 2017-12-20 07:07:50 EDT-------
(In reply to comment #14)
&gt; [root@ltczzj1 ~]# uname -r
&gt; 4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
&gt; 
&gt; [root@ltczzj1 ~]# virsh domcapabilities | grep -i host-model
&gt;     &lt;mode name='host-model' supported='yes'&gt;

As mentioned, am able to reproduce the issue with qemu-kvm-2.11.0-1.rel.gite7153e0.el7.centos.ppc64le

 virsh domcapabilities
&lt;domainCapabilities&gt;
  &lt;path&gt;/usr/bin/qemu-system-ppc64&lt;/path&gt;
  &lt;domain&gt;kvm&lt;/domain&gt;
  &lt;machine&gt;pseries-2.11&lt;/machine&gt;
.,..
  &lt;cpu&gt;
    &lt;mode name='host-passthrough' supported='yes'/&gt;
    &lt;mode name='host-model' supported='no'/&gt;
    &lt;mode name='custom' supported='no'/&gt;
  &lt;/cpu&gt;
...

Regards,
-Satheesh.

**Comment by cdeadmin** [comment] 2018-01-01 09:25
------- Comment From satheera@in.ibm.com 2018-01-01 04:20:11 EDT-------
I found it fixed with below release package levels, Hope this issue is fixed in Upstream aswell?

4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
qemu-kvm-2.11.0-1.rel.gite7153e0.el7.centos.ppc64le
libvirt-3.9.0-1.rel.git99ed075.el7.centos.ppc64le

#virsh domcapabilities
...
.... 
&lt;cpu&gt;
    &lt;mode name='host-passthrough' supported='yes'/&gt;
    &lt;mode name='host-model' supported='yes'&gt;
      &lt;model fallback='allow'&gt;POWER9&lt;/model&gt;
      &lt;vendor&gt;IBM&lt;/vendor&gt;
    &lt;/mode&gt;
    &lt;mode name='custom' supported='no'/&gt;
  &lt;/cpu&gt;

Regards,
-Satheesh

**Comment by cdeadmin** [comment] 2018-01-02 05:15
------- Comment From seg@us.ibm.com 2018-01-02 00:06:52 EDT-------
(In reply to comment #17)
&gt; I found it fixed with below release package levels, Hope this issue is fixed
&gt; in Upstream aswell?
&gt; 
&gt; 4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
&gt; qemu-kvm-2.11.0-1.rel.gite7153e0.el7.centos.ppc64le
&gt; libvirt-3.9.0-1.rel.git99ed075.el7.centos.ppc64le

well, maybe. Would you please retry with the latest daily build? I had to resubmit a new patch.

**Comment by cdeadmin** [comment] 2018-01-04 11:55
------- Comment From satheera@in.ibm.com 2018-01-04 06:48:25 EDT-------
(In reply to comment #18)
&gt; (In reply to comment #17)
&gt; &gt; I found it fixed with below release package levels, Hope this issue is fixed
&gt; &gt; in Upstream aswell?
&gt; &gt; 
&gt; &gt; 4.14.0-1.rel.git68b4afb.el7.centos.ppc64le
&gt; &gt; qemu-kvm-2.11.0-1.rel.gite7153e0.el7.centos.ppc64le
&gt; &gt; libvirt-3.9.0-1.rel.git99ed075.el7.centos.ppc64le
&gt; 
&gt; well, maybe. Would you please retry with the latest daily build? I had to
&gt; resubmit a new patch.

Could you explain more on what is the libvirt version etc, and what difference should I expect?
Any ways in both the version, it is missing Power8 as supported host model - That needs a fix too.

Current daily build libvirt version: 
libvirt-3.9.0-3.dev.gitcb3885f.el7.centos.ppc64le
qemu-2.11.0-1.dev.gite7153e0.el7.centos.ppc64le
4.14.0-3.dev.git68b4afb.el7.centos.ppc64le

# virsh domcapabilities
&lt;domainCapabilities&gt;
  &lt;path&gt;/usr/bin/qemu-kvm&lt;/path&gt;
  &lt;domain&gt;kvm&lt;/domain&gt;
  &lt;machine&gt;pseries-2.11&lt;/machine&gt;
...
...
  &lt;/os&gt;
  &lt;cpu&gt;
    &lt;mode name='host-passthrough' supported='yes'/&gt;
    &lt;mode name='host-model' supported='yes'&gt;
      &lt;model fallback='allow'&gt;POWER9&lt;/model&gt;
      &lt;vendor&gt;IBM&lt;/vendor&gt;
    &lt;/mode&gt;
    &lt;mode name='custom' supported='no'/&gt;
  &lt;/cpu&gt;
  &lt;devices&gt;

-Regards,
-Satheesh.

**Comment by cdeadmin** [comment] 2018-01-08 15:26
------- Comment From seg@us.ibm.com 2018-01-08 10:20:18 EDT-------
(In reply to comment #19)
&gt; Could you explain more on what is the libvirt version etc, and what difference should I expect?
Well, I am currently using libvirt-daemon.ppc64le 3.9.0-3.dev.gitcb3885f.el7.centos

But, I think maybe the difference is that you have a fallback model of POWER9 now. I think that is the objection, and I am not clear that this is allowable.  The primary thing I was looking at, anyway, was the problem where we had   &lt;mode name='host-model' supported='no'/&gt;  which should have been &quot;yes.&quot;

Perhaps Shiva will have a further comment.

**Comment by shiva** [comment] 2018-01-08 19:40
Hi,

Interesting as this is, I can't provide a useful response to you. I am
quite certain you have included the wrong person here.

-Shiva

**Comment by cdeadmin** [comment] 2018-01-08 20:19
------- Comment From seg@us.ibm.com 2018-01-08 15:06:13 EDT-------
(In reply to comment #21)
&gt;
&gt; Hi,
&gt; 
&gt; Interesting as this is, I can't provide a useful response to you. I am
&gt; quite certain you have included the wrong person here.
&gt; 
&gt; -Shiva
&gt; 
&gt; On Jan 8, 2018 7:26 AM, &quot;Application CDEAdmin&quot; &lt;notifications@github.com&gt;
&gt; wrote:
&gt; 
&gt; &gt; (In reply to comment #19)
&gt; &gt; &gt; Could you explain more on what is the libvirt version etc, and what
&gt; &gt; difference should I expect?
&gt; &gt; Well, I am currently using libvirt-daemon.ppc64le
&gt; &gt; 3.9.0-3.dev.gitcb3885f.el7.centos
&gt; &gt;
&gt; &gt; But, I think maybe the difference is that you have a fallback model of
&gt; &gt; POWER9 now. I think that is the objection, and I am not clear that this is
&gt; &gt; allowable. The primary thing I was looking at, anyway, was the problem
&gt; &gt; where we had &lt;mode name='host-model' supported='no'/&gt; which should have
&gt; &gt; been &quot;yes.&quot;
&gt; &gt;
&gt; &gt; Perhaps Shiva will have a further comment.
&gt; &gt;
&gt; &gt; ?
&gt; &gt; You are receiving this because you were mentioned.

Actually, it's hard your response to tell who you are. However, my impression from the comment from github is that the daemon automatically matched some random userid.  -Scott Garfinkle

**Comment by cdeadmin** [comment] 2018-01-16 03:45
------- Comment From seg@us.ibm.com 2018-01-15 22:43:45 EDT-------
The patch has been pulled in to libvirt 4.0. When the sprint completes, we will have all the correct patches in the -release tree, so maybe this will all make more sense (excluding the above github glitches, of course).

**Comment by cdeadmin** [comment] 2018-01-18 15:26
------- Comment From seg@us.ibm.com 2018-01-18 10:16:02 EDT-------
This is done. Fix is in both the current host -devel and -release tree as of libvirt-4.0.0-rc1

------- Comment From seg@us.ibm.com 2018-01-18 10:17:48 EDT-------
If at the latest fix level, there is a problem, please create a new bug. Be explicit about exactly what is happening vs what is expected and at what hardware level it fails.

**Closed as completed by cdeadmin** 2018-01-18 15:26 UTC
